version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ..:/workspace 
      - ~/.gitconfig:/root/.gitconfig
    command: sleep infinity

  db:
    image: postgres
    secrets:
      - postgres-user
      - postgres-password
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password

  adminer:
    image: adminer
    ports:
      - "8080:8080"
  
secrets:
  postgres-user:
    file: ./postgres-user.secret
  postgres-password:
    file: ./postgres-password.secret